[package]
name = "PineBudsAudioReceiverProject"
version = "0.1.0"
edition = "2021"

[dependencies]
serialport = "4.2.2"
chrono = "0.4"
argh = "0.1.13"
once_cell = "1.20.2"
hound = "3.5.1"
ctrlc = "3.4"
byteorder_slice = "3.0.0"
serde = "1.0.217"
serde_json = "1.0.134"
